apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-test-argo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox-test-argo
  template:
    metadata:
      labels:
        app: busybox-test-argo
    spec:
      containers:
        - name: busybox-argo
          image: busybox:1.35-uclibc
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "Hello from BusyBox!" > /data/hello.txt && tail -f /data/hello.txt
          volumeMounts:
            - mountPath: /data
              name: ceph-storage-argo   # Mounting the PVC here
      volumes:
        - name: ceph-storage-argo
          persistentVolumeClaim:
            claimName: ceph-pvc-argo-4  # Reference to the already created PVC
