apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/skroy22/test-app.git'
    targetRevision: HEAD
    path: "test-app"
    auth:
      secretRef:
        name: my-github-creds  # Secret with your GitHub credentials using 
        #sudo microk8s kubectl create secret generic my-github-creds --from-literal=username=skroy.it@gmail.com --from-literal=pa
         #ssword=...... -n argocd 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true