# It was already created through Ansible.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-app-pvc-argo-new
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
#  volumeMode: block
  resources:
    requests:
      storage: 500Mi
  storageClassName: ceph-rbd